version: '3'

services:
  alekssro-web:
    image: ghcr.io/linuxserver/swag
    container_name: alekssro-web
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=alekssro.com
      - EMAIL=alekss.ro@gmail.com
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
    volumes:
      - ./www:/config/www:ro
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
